### ISSUE TITLE
Fix M1 nut

### ISSUE THREAD

**Issue by tpimh** [JohK/nutsnbolts#10]
```
nut("M1");
```

What I expected:
![m1-real](https://user-images.githubusercontent.com/1071872/56461164-e6ddbd00-63b6-11e9-8f26-af68614089ea.png)
What I got:
![m1-openscad](https://user-images.githubusercontent.com/1071872/56461174-0379f500-63b7-11e9-8013-a510a8582d78.png)

**Comment by pcnate** [comment]
did you render with F6?

**Comment by tpimh** [comment]
![Снимок экрана от 2019-04-22 15-31-45](https://user-images.githubusercontent.com/1071872/56500505-cb3bf900-6513-11e9-9398-cdeac05a64fb.png)
Render with F6.

**Comment by pcnate** [comment]
you should post your code. it looks like you have a nut rotated inside of a larger nut

**Comment by tpimh** [comment]
To reproduce:
```
git clone https://github.com/JohK/nutsnbolts.git
cd nutsnbolts
echo 'use <cyl_head_bolt.scad>;\nnut("M1");' > test.scad
```
Then you can open test.scad and see the same results that I got.

**Comment by pcnate** [comment]
Looks like M1 is not defined currently. If you know the proper specs you can add and submit a PR

https://github.com/JohK/nutsnbolts/blob/03f15e5cc470971c2523e7e33e07e6d677605a4e/data-metric_cyl_head_bolts.scad#L34-L40

**Comment by tpimh** [comment]
Thank you! I will try to find technical drawings and add it to the array.

**Comment by JohK** [comment]
Hi,

yes there is no M1 defined in the database.
If I remember correctly the standard only defines M3 onward. 

This can't really be fixed: Another case of where the database is incomplete is bolt length. Actually it covers all bolt lengths from the standard, but manufacturers do offer other lengths...
I guess the fix should be twofold: add bolts to the database and add a warning when the user tries to use a bolt that is not defined.

Please send me a patch for the bolts you added to the database so I can include them.

**Comment by hannesweisbach** [comment]
M1 is actually defined in DIN 934: https://www.schrauben-lexikon.de/norm/DIN_934.asp

**Comment by JohK** [comment]
Hi,

It seems like manufacturers like to extrapolate. DIN 934:1987 has long been withdrawn. I cannot actually find M1 in the current standards, and I doubt they were in the older versions. There is quite some more normative redirections in the documents, but I can't access those.

On one hand, I'm hesitant to just implement some manufacturers table, as they usually provide incomplete data, i.e. they do not list the tolerance bounds... currently, the table in nutsandbolts lists lower bound diameter for bolts and the upper bound diameter for holes/nuts.
On the other hand, for usability and practicability in makes a lot of sense to include those sizes. I'd be fine with just putting the values in the table, if we can double/triple check them with multiple manufacturers. 

(For Info: 
hexagonal head bolts: EN ISO 4014:2010: M1.6 -> M64
cylinder head bolts: EN ISO 4762:2004: M1.6 -> M64
nuts type1: EN ISO 4032:2000: M1.6 -> M64
nuts type2: EN ISO 4033:2000: M5-> M36
nuts thin: EN ISO 4035:2012: MM1.6 -> M64 (and they actually list intermediate sizes that are to avoid *g*)
)

**Comment by hannesweisbach** [comment]
Doesn't DIN912 refer to DIN 13-1 for threads? I don't have access to DIN norms myself :(

I guess it makes sense for resellers to publish partial data of only those items they can actually ship. I checked 5 different vendors and they all agreed on values though.

I guess you mean something like #7 with "lower bound"/"upper bound" diameters?
Imo it's orthogonal to provide those separately (but sensible!).
