### ISSUE TITLE
M3 nut too small

### ISSUE THREAD

**Issue by pwiegele** [JohK/nutsnbolts#12]
Hi,

I was printed a M3 nut und bolt with the commands below
`screw("M3x10", thread="modeled");
nut("M3", thread="modeled");`

The diameter of the nut is too small and I cannot fit the nut on the bolt.
Did I do something wrong?

Cheers Paul

**Comment by hannesweisbach** [comment]
I don't think an FDM-printed M3 thread will ever work. You'd have to use ridiculously small nozzle sizes and layer heights. You might get it to fit if you re-cut the printed thread on the nut and bolt with a thread cutting tool though.

**Comment by JohK** [comment]
Hi,

the intent of this library is: to allow people modelling more complex
models with OpenSCAD to write very explicit and concise code. The library
implements bolts and nuts as defined by standards, there is no optimisation
for printing them (though people have done that).
For printing you may need to adjust some of the tolerance parameters.

Best Regards
Johannes

**Comment by pwiegele** [comment]
Hi,

thanks for pointing this out.
Would it be possible to add a table or set of parameters that has been working for people printing actual nuts and bolts?

I really like this library because it makes creating nuts and bolts easier and more complete.

Cheers Paul
