### ISSUE TITLE
nutcatch_parallel length should default on name

### ISSUE THREAD

**Issue by lluki** [JohK/nutsnbolts#14]
I expected a `nutcatch_parallel("M3")` to just fit the nut (which would be about 2.4mm if [this](https://www.fairburyfastener.com/xdims_metric_nuts.htm) can be trusted). But the default is 5mm independent of the family passed. 

`nutcatch_sidecut` already works this way, I think `nutcatch_parallel` should do the same.

**Comment by JohK** [comment]
Good point.
It's been too long since I wrote this, I can't remember if this was a deliberate decision or just an accidental omission.
Can you provide a patch?

**Comment by wilmardo** [comment]
@JohK This can be closed since #17 is closed, right?
