### ISSUE TITLE
Holes: modelling threads changes position 

### ISSUE THREAD

**Issue by DougCollinge** [JohK/nutsnbolts#3]
I was surprised to find that changing thread="no" to thread="modeled" on a hole_threaded changed its position along Z. Holes with threads unmodeled come with one end at [0,0,0] and the other end on the negative Z axis. Holes with modeled threads are centered on the z axis. 

This was very unexpected behaviour for me! I expected the behaviour given by holes without threads.

translate([5,0,0])
hole_threaded("M5",l=10,thread="no",$fn=30);

translate([-5,0,0])
hole_threaded("M5",l=10,thread="modeled",$fn=30);

**Comment by DougCollinge** [comment]
Relevant code in hole_threaded:
	translate([0,0,-l/2])
	if (thread=="modeled") {
		thread(orad, l, lead);
	} else {
		cylinder(r=irad+cltd/2,h=l,center=true);
	}

I presume that the problem is with "center=true".

**Comment by JohK** [comment]
Thanks for spotting the bug. Actually the thread is displaced, I currently can't put much time into my 3d printing hobby and havent worked with or on the lib for quite a while. I hope I didn't make matters worse with my "fix"... :)

BTW: The intention of the library is to use the penetrated surface as the reference. (aka where would the hole start, or where would the screw head mate with the part...)

**Comment by DougCollinge** [comment]
Thanks! I agree that the surface is the right reference and that's why I thought the behaviour of the hole with modeled threads was weird. I doubt if this is going to cause a problem for anyone because everyone probably uses the threaded hole without the threads modeled. I only noticed it because I was just trying it out to see what it looks like.
