### ISSUE TITLE
nutcatch_sidecut slot width clearance (clsl): what is it, is it even implemented?

### ISSUE THREAD

**Issue by dingo35** [JohK/nutsnbolts#5]
First of all big thumbs up for this library, big THANKS !

I was trying to figure out what the clsl variable in the nutcatch_sidecut module does, but it is only defined as a parameter and seems to be used in no computation at all.... 

Am I overseeing something or is this part not yet implemented?

**Comment by JohK** [comment]
Thanks for spotting that.

It is a bug, currently the slot width clearance is set to the key width clearance. Fixed it.

**Comment by dingo35** [comment]
Thanks Johannes, also for the fix on the notification of the  
deprecated "child" function!

Quoting Johannes Kneer <notifications@github.com>:

> Thanks for spotting that.
>
>   It is a bug, currently the slot width clearance is set to the key  
> width clearance. Fixed it.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       



Links:
------
[1] https://github.com/JohK/nutsnbolts/issues/5#issuecomment-226113680
[2]  
https://github.com/notifications/unsubscribe/AF0kXwbjn4vb-_krvohbmyErHU0vIqnTks5qL66ZgaJpZM4I2D0Z
