### ISSUE TITLE
pls help to confirm some size.

### ISSUE THREAD

**Issue by eexpress** [JohK/nutsnbolts#6]
I want draw a M4 bolt. use this library is so easy, but the size is deferent with standard I am looking for.
I am not skill at bolt standard. Data below is from webpage.

M4.0  / distance 0.70 / MaxD 3.98 / MiniD 3.83  / 3.40

but when I draw a M4, the diameter is only 3.81. <-------------------------

here is my screenshot
https://www.pinterest.com/pin/276408495860470605/

**Comment by JohK** [comment]
Hi,

I'm not quite sure what your complaint is about. How are you measuring, sorry but I can't open the link? The thread is not exactly according to standard and for optical purposes only! 

(btw; The standard gives d_s,min as 3.82 - so we're not that much off... :)
